/*
 * Copyright (c) 2026 Marco Contessotto
 * All rights reserved.
 */

#ifndef SENSORSANDACTUATORS_INCLUDE_SENSORS_AND_ACTUATORS_COMMON_H
#define SENSORSANDACTUATORS_INCLUDE_SENSORS_AND_ACTUATORS_COMMON_H


typedef enum {
	WHEEL_RIGHT,
	WHEEL_LEFT,
} Wheel;

typedef enum{
	WHEEL_FORWARD,
	WHEEL_BACKWARD,
} WheelDirection;


#endif /* SENSORSANDACTUATORS_INCLUDE_SENSORS_AND_ACTUATORS_COMMON_H */
