/*
 * json_writer.c
 *
 *  Created on: Jan 16, 2026
 *      Author: marco
 */

#include <stdio.h>
#include <inttypes.h>

#include "at_command_writer.h"

/* This code was generated by ChatGPT */

typedef struct {
    char  *buf;
    int    size;
    int    off;
    bool   first;
} json_writer_t;

static void jw_init(json_writer_t *jw, char *buf, int size)
{
    jw->buf   = buf;
    jw->size  = size;
    jw->off   = 0;
    jw->first = true;
    jw->buf[jw->off++] = '{';
}

/* write escaped literal (used for keys and separators) */
static inline void jw_write_escaped(json_writer_t *jw, const char *s)
{
    while (*s && jw->off < jw->size - 1) {
        if (*s == '"' || *s == ',') {
            jw->buf[jw->off++] = '\\';
        }
        jw->buf[jw->off++] = *s++;
    }
}

/* write key + separator */
static void jw_key(json_writer_t *jw, const char *key)
{
    if (!jw->first) {
        jw_write_escaped(jw, ",");
    }
    jw->first = false;

    jw_write_escaped(jw, "\"");
    jw_write_escaped(jw, key);
    jw_write_escaped(jw, "\":");
}

static void jw_uint32_t(json_writer_t *jw, uint32_t v)
{
    jw->off += snprintf(jw->buf + jw->off,
                        jw->size - jw->off,
                        "%" PRIu32, v);
}


static void jw_float(json_writer_t *jw, float v)
{
    jw->off += snprintf(jw->buf + jw->off,
                        jw->size - jw->off,
                        "%.4f", v);
}

static int jw_close(json_writer_t *jw)
{
    jw->buf[jw->off++] = '}';
    return jw->off;
}


///////////////////////////////////////////////////////////////
////////////////      CUSTOM FUNCTIONS    /////////////////////
///////////////////////////////////////////////////////////////


int jsonFromPose(const RobottoPose *pose,
                            char *out,
                            int out_size)
{
    json_writer_t jw;

    jw_init(&jw, out, out_size);

    jw_key(&jw, "timestamp");
    jw_uint32_t(&jw, pose->timestamp);

    jw_key(&jw, "x");
    jw_float(&jw, pose->x);

    jw_key(&jw, "y");
    jw_float(&jw, pose->y);

    jw_key(&jw, "theta");
    jw_float(&jw, pose->theta);

    return jw_close(&jw);
}

int atMqttPubFromPose(const RobottoPose *pose,
                      const char *topic,
                      char *out,
                      int out_size)
{
    int off = 0;

    off += snprintf(out, out_size,
                    "AT+MQTTPUB=0,\"%s\",\"",
                    topic);

    off += jsonFromPose(pose,
                           out + off,
                           out_size - off);

    off += snprintf(out + off, out_size - off,
                    "\",0,0");

    return off;
}
