/*
 * Copyright (c) 2026 Marco Contessotto
 * All rights reserved.
 */

#ifndef UNITTESTS_TEST_SUPPORT_ROBOTTO_CONF_H
#define UNITTESTS_TEST_SUPPORT_ROBOTTO_CONF_H

/*
 * THIS IS A MOCK OF THE PARAMETERS USED IN THE LOGIC FUNCTION
 * THE PURPOSE OF THIS FILE IS ONLY TO WRITE UNDESTANDABLE UNIT TESTS
 */

#define WHEELS_RADIUS 1
#define WHEELS_DISTANCE 1

#endif /* UNITTESTS_TEST_SUPPORT_ROBOTTO_CONF_H */
