#ifndef MOCK_CONF_H_
#define MOCK_CONF_H_

/*
 * THIS IS A MOCK OF THE PARAMETERS USED IN THE LOGIC FUNCTION
 * THE PURPOSE OF THIS FILE IS ONLY TO WRITE UNDESTANDABLE UNIT TESTS
 */


#define WHEELS_RADIUS 1
#define WHEELS_DISTANCE 1



#endif /* MOCK_CONF_H_ */
